apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sproxy
rules:
- apiGroups: 
  - ""
  resources:
  - namespaces
  verbs: ["get", "watch", "list"]
- apiGroups:
    - apps
  resources:
    - daemonsets
    - daemonsets/status
    - deployments
    - deployments/scale
    - deployments/status
    - statefulsets
    - statefulsets/scale
    - statefulsets/status
  verbs: ["get", "watch", "list"]
- apiGroups:
    - batch
  resources:
    - cronjobs
    - cronjobs/status
  verbs: ["get", "watch", "list"]
