---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
    app: k8sproxy
  name: k8sproxy
  namespace: k8sproxy
spec:
  selector:
    app: k8sproxy
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: ClusterIP